const $=s=>document.querySelector(s),storageKey='mba-brief-practice';let timerId,seconds=120,currentPractice;let latestBrief=normalizeBrief(window.MBA_BRIEF);
function normalizeBrief(brief){return {...brief,stories:(brief?.stories||[]).map(s=>({...s,contentType:s.contentType||'news',whatIsHappening:s.whatIsHappening||s.whatsHappening||s.summary||'',argument:s.argument||'',otherSide:s.otherSide||'',whyItMatters:s.whyItMatters||s.why||'',howToThinkAboutIt:s.howToThinkAboutIt||(Array.isArray(s.context)?s.context.join(' '):''),keyFacts:s.keyFacts||s.facts||[],questionToThinkAbout:s.questionToThinkAbout||s.question||''}))}}
function formatDate(d=new Date()){return d.toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}
function formatUpdated(value){if(!value)return'Not available';const date=new Date(value);return Number.isNaN(date.getTime())?'Not available':date.toLocaleString('en-IN',{day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit',timeZone:'Asia/Kolkata',timeZoneName:'short'})}
function renderStories(){const brief=latestBrief;$('#stories').innerHTML=brief.stories.map((s,i)=>`<article class="story"><div class="story-index">0${i+1}</div><div><p class="source"><a href="${s.url}" target="_blank" rel="noopener">${s.source}</a><span>${s.contentType} · ${formatUpdated(s.publishedAt)}</span></p><h3>${s.title}</h3><p class="detail-label">Issue</p><p class="issue">${s.issue}</p></div><div class="story-detail"><p class="detail-label">What’s happening</p><p>${s.whatIsHappening}</p>${s.argument?`<br><p class="detail-label">The argument</p><p>${s.argument}</p>`:''}${s.otherSide?`<br><p class="detail-label">The other side</p><p>${s.otherSide}</p>`:''}<br><p class="detail-label">Why it matters</p><p>${s.whyItMatters}</p></div><div class="story-detail"><p class="detail-label">How to think about it</p><p>${s.howToThinkAboutIt}</p><p class="detail-label facts-label">Key facts / numbers</p><ul class="facts">${s.keyFacts.map(x=>`<li>${x}</li>`).join('')}</ul><p class="detail-label question-label">One question to think about</p><p class="angle">${s.questionToThinkAbout}</p></div></article>`).join('');$('#brief-updated').textContent=`Last updated: ${formatUpdated(brief.lastSuccessfulRefresh||brief.generatedAt)} · ${brief.stories.length} stories`}
function renderExtempore(){const x=latestBrief.extempore||{};$('#extempore-card').innerHTML=`<div><span class="topic-tag">One debatable issue</span><h3>${x.issue||'No extempore topic available'}</h3><p class="why-now"><strong>Why now</strong><br>${x.whyNow||''}</p><button class="button primary" id="start-practice">Start 2-minute extempore <span>→</span></button></div><div><div class="extempore-columns"><div><h4>Supporting the case</h4><ul>${(x.argumentsFor||[]).map(v=>`<li>${v}</li>`).join('')}</ul></div><div><h4>Challenging the case</h4><ul>${(x.argumentsAgainst||[]).map(v=>`<li>${v}</li>`).join('')}</ul></div></div><div class="examples"><h4>Useful examples</h4><ul>${(x.examples||[]).map(v=>`<li>${v}</li>`).join('')}</ul></div><div class="facts-panel"><h4>Facts / numbers</h4><ul>${(x.facts||[]).map(v=>`<li>${v}</li>`).join('')}</ul></div><div class="structure"><strong>Suggested 2-minute structure</strong><br>${x.structure||''}</div></div></div>`;$('#start-practice').onclick=openPractice}
function getHistory(){try{return JSON.parse(localStorage.getItem(storageKey)||'[]')}catch{return[]}}
function renderHistory(){const h=getHistory();$('#history-count').textContent=h.length;$('#history-summary').textContent=`${h.length} session${h.length===1?'':'s'} saved locally`;$('#history-list').innerHTML=h.length?h.map(x=>`<article class="history-item"><div class="history-date">${x.date}</div><div><h3>${x.topic}</h3><p class="history-answer">${x.answer||'No written answer saved.'}</p>${x.notes?`<p class="history-answer"><strong>Note:</strong> ${x.notes}</p>`:''}</div><div class="completed">${x.completed?'Completed':'Started'}</div></article>`).join(''):'<p class="history-empty">No sessions yet. Your practiced topics will appear here.</p>'}
function openPractice(){currentPractice={topic:latestBrief.extempore.issue};seconds=120;$('#practice-title').textContent=currentPractice.topic;$('#practice-active').classList.remove('hidden');$('#review-panel').classList.add('hidden');$('#answer').value='';$('#review-notes').value='';$('#practice-modal').classList.remove('hidden');updateTimer();clearInterval(timerId);timerId=setInterval(()=>{seconds--;updateTimer();if(seconds<=0)clearInterval(timerId)},1000)}
function updateTimer(){const m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');$('#timer').textContent=`${m}:${s}`;$('#timer-progress').style.width=`${seconds/120*100}%`}
function finishPractice(){clearInterval(timerId);$('#practice-active').classList.add('hidden');$('#review-panel').classList.remove('hidden');const items=['Did I clearly define the issue?','Did I consider both sides?','Did I use at least one concrete example?','Did I give my own position?','Did I conclude clearly?'];$('#checklist').innerHTML=items.map((x,i)=>`<label class="check-row"><input type="checkbox" id="check-${i}">${x}</label>`).join('')}
function savePractice(){const checks=[0,1,2,3,4].filter(i=>$(`#check-${i}`).checked).length,h=getHistory();h.unshift({date:formatDate(),topic:currentPractice.topic,answer:$('#answer').value,notes:$('#review-notes').value,completed:true,checks});localStorage.setItem(storageKey,JSON.stringify(h));closePractice();renderHistory()}
function closePractice(){clearInterval(timerId);$('#practice-modal').classList.add('hidden')}
function switchView(view){const today=view==='today';$('#today-view').classList.toggle('hidden',!today);$('#history-view').classList.toggle('hidden',today);document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.view===view));if(!today)renderHistory()}
async function fetchBrief(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(`${path} unavailable`);const brief=normalizeBrief(await response.json());if(!brief.stories.length)throw new Error(`${path} empty`);return brief}
async function loadLatest(){try{latestBrief=await fetchBrief('/data/today.json');renderStories();renderExtempore()}catch{ /* bundled seed remains active */ }}
document.addEventListener('click',e=>{const link=e.target.closest('[data-view]');if(link){e.preventDefault();switchView(link.dataset.view);history.replaceState(null,'',`#${link.dataset.view}`)}});$('#close-modal').onclick=closePractice;$('#cancel-practice').onclick=closePractice;$('#finish-practice').onclick=finishPractice;$('#save-practice').onclick=savePractice;$('#refresh-brief').onclick=async()=>{const button=$('#refresh-brief');button.textContent='↻ Refreshing';try{latestBrief=await fetchBrief('/data/today.json');renderStories();renderExtempore()}catch{latestBrief=normalizeBrief(window.MBA_BRIEF);renderStories();renderExtempore()}button.textContent='↻ Refreshed'};$('#practice-modal').addEventListener('click',e=>{if(e.target.id==='practice-modal')closePractice()});$('#header-date').textContent=formatDate();$('#hero-date').textContent=formatDate();renderStories();renderExtempore();renderHistory();if(location.hash==='#history')switchView('history');loadLatest();
