const crypto=require('crypto');
function sentences(text){return String(text||'').split(/(?<=[.!?])\s+/).map(value=>value.trim()).filter(Boolean)}
function inferContentType(article,title,summary){if(article.contentType)return article.contentType;const signal=`${article.category||''} ${title} ${summary}`.toLowerCase();if(/\b(opinion|editorial|column|commentary)\b/.test(signal))return'opinion';if(/\b(analysis|perspective|outlook|why it matters)\b/.test(signal))return'analysis';if(/\b(explained|explainer|what to know)\b/.test(signal))return'explainer';return'news'}
function inferDebatePotential(article,contentType,title,summary){if(Number.isFinite(Number(article.debatePotential)))return Number(article.debatePotential);const signal=`${title} ${summary} ${article.category||''}`.toLowerCase();let score={opinion:7,analysis:6,explainer:4,news:2}[contentType]||2;['policy','trade','tariff','inflation','energy','climate','geopolit','regulation','strategy','should','whether','risk','jobs','growth','security','china','america','india'].forEach(word=>{if(signal.includes(word))score+=.35});return Math.min(10,Math.round(score*10)/10)}
function normalizeArticle(article){const title=String(article.title||'').trim(),summary=String(article.summary||article.description||'').trim();if(!title||!article.url)return null;const contentType=inferContentType(article,title,summary),context=Array.isArray(article.context)&&article.context.length?article.context:sentences(summary).slice(0,3);return {id:article.id||crypto.createHash('sha1').update(`${title}|${article.url}`).digest('hex').slice(0,12),title,url:article.url,source:article.source||'Unknown source',publishedAt:article.publishedAt||article.pubDate||new Date().toISOString(),category:article.category||'Current affairs',contentType,debatePotential:inferDebatePotential(article,contentType,title,summary),summary,issue:article.issue||`What should decision-makers do about ${title.replace(/[.!?]+$/,'')}?`,whatsHappening:article.whatsHappening||summary,argument:article.argument||'',otherSide:article.otherSide||'',whyItMatters:article.whyItMatters||summary,context,keyFacts:Array.isArray(article.keyFacts)?article.keyFacts:[],questionToThinkAbout:article.questionToThinkAbout||`What is the broader consequence of ${title.replace(/[.!?]+$/,'')}?`,questionPotential:Number(article.questionPotential)||0,credibilityWeight:Number(article.credibilityWeight)||0,editorialWeight:Number(article.editorialWeight)||0}}
function canonicalUrl(url){return url.replace(/^https?:\/\/(www\.)?/,'').replace(/[?#].*$/,'').replace(/\/$/,'').toLowerCase()}
function titleTokens(title){return new Set(String(title).toLowerCase().replace(/[^a-z0-9\s]/g,'').split(/\s+/).filter(word=>word.length>3&&!['india','will','what','from','after','about','into','this','that','with'].includes(word)))}
function titleSimilarity(a,b){const left=titleTokens(a),right=titleTokens(b),intersection=[...left].filter(token=>right.has(token)).length;return intersection/Math.max(1,Math.min(left.size,right.size))}
function dedupeArticles(articles){const seenUrls=new Set(),kept=[];for(const raw of articles){const article=normalizeArticle(raw);if(!article)continue;const url=canonicalUrl(article.url);if(seenUrls.has(url))continue;const duplicate=kept.find(existing=>titleSimilarity(existing.title,article.title)>=0.45);if(duplicate){if((article.credibilityWeight+article.editorialWeight)>(duplicate.credibilityWeight+duplicate.editorialWeight))kept[kept.indexOf(duplicate)]=article;continue}seenUrls.add(url);kept.push(article)}return kept}
function freshnessFilter(articles,{now=new Date(),maxHours=24,expandedHours=48}={}){const dated=articles.filter(article=>{const age=(now-new Date(article.publishedAt))/36e5;return Number.isFinite(age)&&age>=-2&&age<=expandedHours});const fresh=dated.filter(article=>(now-new Date(article.publishedAt))/36e5<=maxHours);return fresh.length>=5?fresh:dated}
function scoreStory(story){const text=`${story.title} ${story.issue} ${story.category} ${story.summary}`.toLowerCase();const keywords=['india','trade','tariff','policy','economy','inflation','energy','oil','climate','geopolit','supply chain','semiconductor','ai','technology','security','election'];const relevance=keywords.filter(word=>text.includes(word)).length;const typeWeight={opinion:8,analysis:7,explainer:5,news:2}[story.contentType]||2;const debate=Number(story.debatePotential)||0;return typeWeight+debate+(story.questionPotential||0)*.5+(story.credibilityWeight||0)*2+(story.editorialWeight||0)+Math.min(relevance,5)+(story.context.length>=2?1:0)+(story.issue.includes('India')?1:0)}
function selectStories(articles,limit=5,options={}){const pool=freshnessFilter(dedupeArticles(articles),options);return pool.sort((a,b)=>scoreStory(b)-scoreStory(a)).slice(0,limit)}
function buildExtempore(stories){const top=[...stories].sort((a,b)=>(b.debatePotential||0)-(a.debatePotential||0))[0];if(!top)return null;return {issue:top.questionToThinkAbout,whyNow:top.whatsHappening||top.summary,argumentsFor:top.argumentsFor||[],argumentsAgainst:top.argumentsAgainst||[],examples:top.examples||[],facts:top.keyFacts.length?top.keyFacts:sentences(top.summary).slice(0,3),structure:'Opening → Context → Argument 1 → Argument 2 → Counterargument → Conclusion',sourceBasis:{source:top.source,url:top.url,contentType:top.contentType}}}
function buildBrief({articles,extempore,generatedAt=new Date().toISOString(),now=new Date()}){const stories=selectStories(articles,5,{now});if(!stories.length)throw new Error('No fresh usable articles returned');return {generatedAt,lastSuccessfulRefresh:generatedAt,stories,extempore:extempore||buildExtempore(stories)}}
async function refreshBrief({fetchArticles,extempore,now=new Date()}){const articles=await fetchArticles();if(!Array.isArray(articles)||!articles.length)throw new Error('No usable articles returned');return buildBrief({articles,extempore,now})}
module.exports={normalizeArticle,dedupeArticles,titleSimilarity,freshnessFilter,scoreStory,selectStories,buildExtempore,buildBrief,refreshBrief,inferContentType,inferDebatePotential};
