const {URL}=require('url');
function strip(value=''){return value.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&#x27;/gi,"'").replace(/\s+/g,' ').trim()}
function tag(block,name){const match=block.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,'i'));return match?strip(match[1]):''}
function link(block){const atom=block.match(/<link[^>]+href=["']([^"']+)["'][^>]*\/?\s*>/i);return atom?atom[1]:tag(block,'link')}
function parseFeed(xml,feed){if(!xml||!/<(item|entry)\b/i.test(xml))return[];const blocks=xml.match(/<(?:item|entry)\b[\s\S]*?<\/(?:item|entry)>/gi)||[];return blocks.map(block=>{const title=tag(block,'title');const url=link(block);const publishedAt=tag(block,'pubDate')||tag(block,'published')||tag(block,'updated')||tag(block,'dc:date');const summary=tag(block,'description')||tag(block,'summary')||tag(block,'content:encoded');return title&&url?{title,url:resolveUrl(url,feed.url),source:feed.name,publishedAt,summary,category:feed.category,contentType:feed.contentType,credibilityWeight:feed.credibilityWeight,editorialWeight:feed.editorialWeight}:null}).filter(Boolean)}
function resolveUrl(value,base){try{return new URL(value,base).toString()}catch{return value}}
async function fetchFeed(feed,{fetchImpl=global.fetch,timeoutMs=10000}={}){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetchImpl(feed.url,{headers:{accept:'application/rss+xml, application/atom+xml, application/xml, text/xml'},signal:controller.signal});if(!response.ok)throw new Error(`${feed.name} returned HTTP ${response.status}`);return parseFeed(await response.text(),feed)}finally{clearTimeout(timeout)}}
async function fetchAllFeeds(feeds,{fetchImpl=global.fetch}={}){const results=await Promise.allSettled(feeds.filter(feed=>feed.enabled).map(feed=>fetchFeed(feed,{fetchImpl})));return {articles:results.flatMap(result=>result.status==='fulfilled'?result.value:[]),failures:results.flatMap((result,index)=>result.status==='rejected'?[feeds.filter(feed=>feed.enabled)[index].name]:[])}}
module.exports={strip,parseFeed,fetchFeed,fetchAllFeeds};
